### ISSUE TITLE
Truncation of '::' when rewriting a constant defined outside of the "module/class end" bloc

### ISSUE THREAD

**Issue by pw-rey** [NuriYuri/rust_ruby_code_writer#1]
When trying to rewrite a constant defined this way: 
```ruby
NameModule::NameClass::Constant = value
```
the output gets truncated of any '::' after the first ones.
Here is an example of the original code and the result:
![image](https://github.com/NuriYuri/rust_ruby_code_writer/assets/71990106/53bc4272-6550-4c11-881a-5d784c2945b5)
![image](https://github.com/NuriYuri/rust_ruby_code_writer/assets/71990106/5fdba142-bb08-4bf9-8f11-20dfbd462736)

This sort of issue can be harder to detect because the code is technically correct, until we're trying to access it or monkey-patch it.

**Comment by NuriYuri** [comment]
Related commit: https://github.com/NuriYuri/rust_ruby_code_writer/commit/e0be81383fb472188de9d4a1271a4d030e64bd41
Needs to be tested with a new release of PSDK (but before I'm fixing other stuff that are due to the converter).

**Comment by pw-rey** [comment]
Alright, I'll wait for the next batch of fixes before testing. :)

**Comment by NuriYuri** [comment]
Fixé selon tests
